Repository MARKETProtocol/dApp, pull requests merged in 2018-06, with the labels that each got.

#186 Update market-solidity to 1.0.1
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
  rinkeby-build/contracts/Authentication.json
  rinkeby-build/contracts/CollateralToken.json
  rinkeby-build/contracts/Destructible.json
  rinkeby-build/contracts/MarketCollateralPoolFactory.json
  rinkeby-build/contracts/MarketContractFactoryOraclize.json
  rinkeby-build/contracts/MarketContractOraclize.json
  rinkeby-build/contracts/MarketContractRegistry.json
  rinkeby-build/contracts/MarketToken.json
  rinkeby-build/contracts/MathLib.json
  rinkeby-build/contracts/Migrations.json
  rinkeby-build/contracts/OraclizeQueryTest.json
  rinkeby-build/contracts/OrderLib.json
  rinkeby-build/contracts/Ownable.json
  src/Contracts.js
  src/actions/deploy.js
  src/components/ContractsList.js
  src/components/DeployContract/DeployContractField.js
  src/components/DeployContract/GuidedDeployment.js
  src/components/DeployContract/QuickDeployment.js
  src/components/DeployContract/SimplifiedDeployment.js
  src/components/DeployContract/Steps.js
  src/components/FindContract/FindContractForm.js
  src/util/utils.js
  test/actions/deploy.test.js
  test/actions/explorer.test.js
  test/actions/find.test.js
  test/components/ContractsList.test.js
  test/components/DeployContract/QuickDeployment.test.js
  test/mocks/contracts.js
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#190 Extend simplified deployment to allow for assets denominated in USDT
  src/components/DeployContract/ExchangeSources.js
  src/components/DeployContract/SelectTokenField.js
  src/components/DeployContract/SimplifiedDeployment.js
  src/util/utils.js
  test/util/utils.test.js
Labels: Priority: Medium, Status: Completed

#199 add bucket cleanup and cloudfront invalidation script
  .travis.yml
  scripts/clean_bucket.sh
Labels: Priority: High, Status: Completed

#202 Fix selected deployment contract state in Header component
  package-lock.json
  src/components/Header.js
  src/components/NavItem.js
  test/components/NavItem.test.js
Labels: Priority: Medium, Status: Review Needed, Type: Bug
