Repository MARKETProtocol/dApp, pull requests merged in 2018-07, with the labels that each got.

#198 Modify the UX flow for deploying contract #187
  package-lock.json
  package.json
  src/actions/deploy.js
  src/components/DeployContract/DeployContractForm.js
  src/components/DeployContract/GuidedDeployment.js
  src/components/DeployContract/QuickDeployment.js
  src/components/DeployContract/SimplifiedDeployment.js
  src/components/DeployContract/Steps.js
  src/containers/Deploy.js
  src/less/ContractDeploymentFlow.less
  src/reducers/deploy.js
  test/actions/deploy.test.js
  test/components/DeployContract/QuickDeployment.test.js
  test/components/DeployContract/Steps.test.js
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#233 Updated the url references to point to the market-api proxy for Bitfinex
  src/components/DeployContract/ExchangeSources.js
Labels: Status: Review Needed, Type: Enhancement

#236 Fix/deploy flow
  package-lock.json
  src/components/DeployContract/GuidedDeployment.js
  src/components/DeployContract/QuickDeployment.js
  src/components/DeployContract/SimplifiedDeployment.js
  src/components/DeployContract/Steps.js
  src/containers/Deploy.js
  src/util/utils.js
  test/util/utils.test.js
Labels: Status: Review Needed, review

#225 Maker Order Placement
  package-lock.json
  package.json
  src/actions/simExchange.js
  src/components/DeployContract/SimplifiedDeployment.js
  src/components/DeployContract/Steps.js
  src/components/SimExchange/Columns.js
  src/components/SimExchange/SimExchange.js
  src/components/SimExchange/TradeComponents/Form.js
  src/components/SimExchange/TradeContainer.js
  src/components/SimExchange/Trades.js
  src/components/SimExchange/Trades.less
  src/components/SimExchange/WalletComponents/HeaderMenu.js
  src/containers/SimExchange.js
  src/index.js
  src/less/App.less
  src/less/Trades.less
  src/reducers/index.js
  src/reducers/simExchange.js
  src/util/marketjs/initializeMarket.js
  src/util/marketjs/marketMiddleware.js
  src/util/marketjs/marketReducer.js
  src/util/utils.js
  test/actions/simExchange.test.js
  test/components/SimExchange/SimExchange.test.js
  test/components/SimExchange/Trades.test.js
  test/components/SimExchange/Wallet.test.js
  test/reducers/simExchange.test.js
  test/util/marketjs/initializeMarket.test.js
  test/util/marketjs/marketReducer.test.js
Labels: Status: Review Needed

#256 Replace Base Token with Collateral Token
  src/components/ContractsList.js
  src/components/DeployContract/DeployContractField.js
  src/components/DeployContract/Steps.js
  test/components/DeployContract/Steps.test.js
Labels: review

#278 Updates React lifecycle methods
  src/App.js
  src/components/DeployContract/DeployContractSuccess.js
  src/components/DeployContract/ExchangeSources.js
  src/components/DeployContract/SelectTokenField.js
  src/components/FindContract/FindContractForm.js
  src/components/SimExchange/SimExchange.js
  src/components/SimExchange/Trades.js
  src/components/SimExchange/WalletComponents/HeaderMenu.js
  src/components/SimExchange/WalletComponents/Table.js
  src/components/TestQuery/TestQueryForm.js
  src/components/TestQuery/TestQuerySuccess.js
  src/util/contracts.js
Labels: Status: Review Needed
